# Generated by Django 2.0.2 on 2018-02-22 16:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brewing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date Packaged')),
                ('end_date', models.DateField(blank=True, default='', verbose_name='Age Until This Date')),
                ('packager', models.CharField(blank=True, choices=[('tyler', 'Tyler'), ('ron', 'Ron'), ('chris', 'Chris'), ('shea', 'Shea'), ('ian', 'Ian'), ('brandon', 'Brandon')], max_length=100, null=True, verbose_name='packager')),
                ('barrel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brewing.Barrel')),
                ('batches', models.ManyToManyField(blank=True, help_text='Batches sourced.', null=True, to='brewing.Batch', verbose_name='Source Batches')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date Packaged')),
                ('packager', models.CharField(blank=True, choices=[('tyler', 'Tyler'), ('ron', 'Ron'), ('chris', 'Chris'), ('shea', 'Shea'), ('ian', 'Ian'), ('brandon', 'Brandon')], max_length=100, null=True, verbose_name='packager')),
                ('format_type', models.CharField(blank=True, choices=[('12oz/CS', '12oz/CS'), ('16oz/CS', '16oz/CS'), ('375ml/CS', '375ml/CS'), ('500ml/CS', '500ml/CS'), ('750ml/CS', '750ml/CS'), ('1/6bbl', '1/6bbl'), ('1/4bbl', '1/4bbl'), ('1/2bbl', '1/2bbl'), ('50l', '50l'), ('Firkin (10.8g)', 'Firkin (10.8g)'), ('Pin (5.4g)', 'Pin (5.4g)')], max_length=20, null=True, verbose_name='Format')),
                ('format_qty', models.DecimalField(blank=True, decimal_places=2, help_text='Total packaged quantity for this format in cases/units (NOT BBL).', max_digits=10, null=True, verbose_name='Packaged Units')),
                ('batches', models.ManyToManyField(blank=True, help_text='Batches associated with this packaging event.', null=True, to='brewing.Batch', verbose_name='Source Batches')),
            ],
        ),
    ]
