# Generated by Django 2.0.2 on 2018-09-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-package_date']},
        ),
        migrations.AddField(
            model_name='package',
            name='oxygen_log',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter measured oxygen (ppb).', max_digits=5, null=True, verbose_name='Packaging Oxygen Log'),
        ),
    ]
