# Generated by Django 2.0.2 on 2018-02-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='batches',
            field=models.ManyToManyField(blank=True, help_text='Batches associated with this packaging event.', null=True, to='brewing.Batch', verbose_name='Source Batches'),
        ),
    ]
