# Generated by Django 2.0.2 on 2018-02-20 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0004_aging'),
    ]

    operations = [
        migrations.AddField(
            model_name='aging',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Age Until This Date'),
        ),
        migrations.AddField(
            model_name='aging',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date Packaged'),
        ),
    ]
