# Generated by Django 2.0.2 on 2018-02-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0005_auto_20180220_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aging',
            name='end_date',
            field=models.DateField(blank=True, default='', verbose_name='Age Until This Date'),
        ),
    ]
