# Generated by Django 2.0.2 on 2018-02-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brix',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=14, null=True, verbose_name='Brix reading'),
        ),
        migrations.AlterField(
            model_name='brix',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=14, null=True, verbose_name='@ volume'),
        ),
    ]
