# Generated by Django 2.0.2 on 2018-02-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='double_batch',
            field=models.BooleanField(default=False, verbose_name='Double-batch?'),
        ),
    ]
