# Generated by Django 2.0.2 on 2018-02-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0002_auto_20180222_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry_type',
        ),
    ]
