# Generated by Django 2.0.2 on 2018-02-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0003_auto_20180219_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermentable',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Weight of the fermentable, extract or sugar in pounds.', max_digits=14, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='hop',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Weight in pounds of the hops used in the recipe.', max_digits=14, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='misc',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount of item used. The default measurements are by weight, \n            but this may be the measurement in volume units if AMOUNT_IS_WEIGHT is set \n            to TRUE for this record. For liquid items this is liters, for solid the  \n            weight is measured in kilograms.', max_digits=14, verbose_name='yield percentage'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Weight in ounces of the salt used in the recipe.', max_digits=14, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='yeast',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The amount of yeast, measured in liters. For a starter this is the \n            size of the starter. If the flag AMOUNT_IS_WEIGHT is set to TRUE then this \n            measurement is in kilograms and not liters.', max_digits=14, verbose_name='amount'),
        ),
    ]
