# Generated by Django 2.0.2 on 2018-02-22 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0003_remove_entry_entry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='cdt',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='mdt',
        ),
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
