# Generated by Django 2.0.2 on 2018-02-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0004_auto_20180220_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='brixes',
        ),
        migrations.AddField(
            model_name='batch',
            name='brix_log',
            field=models.TextField(blank=True, help_text='Enter Brix readings/notes here.', null=True, verbose_name='Brix Log'),
        ),
        migrations.AddField(
            model_name='batch',
            name='cellaring_log',
            field=models.TextField(blank=True, help_text='Enter any cellaring notes here.', null=True, verbose_name='Cellaring Log'),
        ),
        migrations.AddField(
            model_name='batch',
            name='gravity_log',
            field=models.TextField(blank=True, help_text='Enter gravity readings here.', null=True, verbose_name='Gravity Log'),
        ),
        migrations.AddField(
            model_name='batch',
            name='transfer_log',
            field=models.TextField(blank=True, help_text='Enter transfer notes here.', null=True, verbose_name='Transfer Log'),
        ),
        migrations.AddField(
            model_name='batch',
            name='yeast_gen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Yeast Generation'),
        ),
        migrations.AddField(
            model_name='batch',
            name='yeast_log',
            field=models.TextField(blank=True, help_text='Enter yeast notes here.', null=True, verbose_name='Yeast Log'),
        ),
        migrations.AddField(
            model_name='batch',
            name='yeast_origin_gyle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Yeast Origin Gyle'),
        ),
        migrations.AddField(
            model_name='batch',
            name='yeast_type',
            field=models.CharField(choices=[('001', '001'), ('3470', '3470'), ('other', 'Other')], default='001', max_length=100, verbose_name='Yeast Type'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='notes',
            field=models.TextField(blank=True, help_text='Enter batch notes here.', null=True, verbose_name='Batch Notes'),
        ),
        migrations.DeleteModel(
            name='Brix',
        ),
    ]
