# Generated by Django 2.0.2 on 2018-02-22 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0004_auto_20180222_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='current_tank',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='yeast_gen',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='yeast_log',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='yeast_origin_gyle',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='yeast_type',
        ),
        migrations.AddField(
            model_name='batch',
            name='attenuation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Attenuation %.', max_digits=5, null=True, verbose_name='Attenuation %'),
        ),
        migrations.AddField(
            model_name='batch',
            name='ferm_tank',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_batch_tank', to='brewing.Container', verbose_name='Ferm. Tank'),
        ),
        migrations.AddField(
            model_name='batch',
            name='final_abv',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final abv.', max_digits=5, null=True, verbose_name='Final abv'),
        ),
        migrations.AddField(
            model_name='batch',
            name='final_gravity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final gravity.', max_digits=5, null=True, verbose_name='Final gravity'),
        ),
    ]
