# Generated by Django 2.0.2 on 2018-02-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0005_auto_20180220_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='container_type',
            field=models.CharField(choices=[('F', 'Fermentation'), ('B', 'Brite'), ('A', 'Aging')], default='F', max_length=100, verbose_name='Container Type'),
        ),
    ]
