# Generated by Django 2.0.2 on 2018-02-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0005_auto_20180222_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='brix_1_val',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Initial Brix Reading.', max_digits=5, null=True, verbose_name='Initial Brix Reading'),
        ),
        migrations.AddField(
            model_name='batch',
            name='brix_1_vol',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Initial Brix Volume.', max_digits=5, null=True, verbose_name='Initial Brix Volume'),
        ),
        migrations.AddField(
            model_name='batch',
            name='brix_2_val',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Second Brix Reading.', max_digits=5, null=True, verbose_name='Second Brix Reading'),
        ),
        migrations.AddField(
            model_name='batch',
            name='brix_2_vol',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Second Reading Volume.', max_digits=5, null=True, verbose_name='Second Reading Volume'),
        ),
    ]
