# Generated by Django 2.0.2 on 2018-02-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0006_auto_20180222_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='brix_3_val',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final Brix Reading.', max_digits=5, null=True, verbose_name='Second Brix Reading'),
        ),
        migrations.AddField(
            model_name='batch',
            name='brix_3_vol',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final Reading Volume.', max_digits=5, null=True, verbose_name='Second Reading Volume'),
        ),
    ]
