# Generated by Django 2.0.2 on 2018-02-20 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0006_container_container_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrel',
            fields=[
                ('container_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brewing.Container')),
                ('spirit_profile', models.CharField(choices=[('B', 'Bourbon'), ('B/M', 'Bourbon/Maple'), ('G', 'Gin'), ('R', 'Rum'), ('T', 'Tequila'), ('W', 'Whiskey'), ('SMW', 'Single Malt Whiskey')], default='B/M', max_length=100, verbose_name='Spirit profile')),
                ('manufacturer', models.CharField(blank=True, choices=[('KC', 'Kelvin Cooperage'), ('BS', 'Black Swan'), ('U', 'Unknown'), ('O', 'Other')], max_length=100, null=True, verbose_name='Manufacturer')),
                ('distiller', models.CharField(blank=True, choices=[('WR', 'Woodfords Reserve'), ('RD', 'River Driver'), ('MCD', 'Maine Craft Distillery')], max_length=100, null=True, verbose_name='Distiller')),
            ],
            options={
                'abstract': False,
            },
            bases=('brewing.container',),
        ),
    ]
