# Generated by Django 2.0.2 on 2018-02-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0007_auto_20180222_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='gravity_log',
        ),
        migrations.AddField(
            model_name='batch',
            name='brite_tank',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_brite_tank', to='brewing.Container', verbose_name='Brite Tank'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='brix_3_val',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final Brix Reading.', max_digits=5, null=True, verbose_name='Final Brix Reading'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='brix_3_vol',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final Reading Volume.', max_digits=5, null=True, verbose_name='Final Reading Volume'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='ferm_tank',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_ferm_tank', to='brewing.Container', verbose_name='Ferm. Tank'),
        ),
        migrations.RemoveField(
            model_name='batch',
            name='transfer_log',
        ),
        migrations.AddField(
            model_name='batch',
            name='transfer_log',
            field=models.TextField(blank=True, help_text='Enter any transfer notes here.', null=True, verbose_name='Transfer Log'),
        ),
    ]
