# Generated by Django 2.0.2 on 2018-02-22 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0008_auto_20180222_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='brix_log',
        ),
        migrations.AlterField(
            model_name='batch',
            name='brite_tank',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'container_type': 'B'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_brite_tank', to='brewing.Container', verbose_name='Brite Tank'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='double_batch',
            field=models.BooleanField(default=False, help_text='Tick this box to create a second batch on save.', verbose_name='Is this a double-batch?'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='ferm_tank',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'container_type': 'F'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_ferm_tank', to='brewing.Container', verbose_name='Fermentation Tank'),
        ),
    ]
