# Generated by Django 2.0.2 on 2018-02-22 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0010_auto_20180222_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='transfer_tank',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'container_type': 'A'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='brewing.Container', verbose_name='Transfer Tank'),
        ),
    ]
