# Generated by Django 2.0.2 on 2018-02-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0012_auto_20180222_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='post_transfer_vol',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Post Transfer Batch Volume.', max_digits=5, null=True, verbose_name='Post Transfer Batch Volume'),
        ),
        migrations.AddField(
            model_name='batch',
            name='pre_transfer_vol',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pre Transfer Batch Volume.', max_digits=5, null=True, verbose_name='Pre Transfer Batch Volume'),
        ),
    ]
