# Generated by Django 2.0.2 on 2018-02-22 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0013_auto_20180222_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='recipe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='brewing.Recipe'),
        ),
    ]
