# Generated by Django 2.0.2 on 2018-02-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0015_auto_20180226_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fermentable',
            name='coarse_fine_diff',
        ),
        migrations.RemoveField(
            model_name='fermentable',
            name='diastatic_power',
        ),
        migrations.RemoveField(
            model_name='fermentable',
            name='ibu_gal_per_lb',
        ),
        migrations.RemoveField(
            model_name='fermentable',
            name='max_in_batch',
        ),
        migrations.RemoveField(
            model_name='fermentable',
            name='moisture',
        ),
        migrations.RemoveField(
            model_name='fermentable',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='fermentable',
            name='recommend_mash',
        ),
    ]
