# Generated by Django 2.0.2 on 2018-02-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0016_auto_20180226_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='transfer_cip',
            field=models.BooleanField(default=False, help_text='Tick this box if the destination container was cleaned prior to transfer.', verbose_name='CIP?'),
        ),
    ]
