# Generated by Django 2.0.2 on 2018-02-26 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0017_auto_20180226_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='ferm_tank',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'container_type': 'F'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_ferm_tank', to='brewing.Container', verbose_name='Fermentation Tank'),
        ),
    ]
