# Generated by Django 2.0.2 on 2018-03-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0018_auto_20180226_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='hop',
            name='amt_units',
            field=models.CharField(choices=[('LB', 'Pounds(lb)'), ('BU', 'Bittering Units(BU)')], default='LB', help_text='The unit of measure used for this hop instance.', max_length=50, verbose_name='Units'),
        ),
    ]
