# Generated by Django 2.0.2 on 2018-03-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0021_auto_20180307_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='pre_transfer_vol',
        ),
        migrations.AlterField(
            model_name='batch',
            name='d_rest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='first_dry_hop',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='second_dry_hop',
            field=models.DateField(blank=True, null=True),
        ),
    ]
