# Generated by Django 2.0.2 on 2018-09-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0022_auto_20180321_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='post_boil_ph',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter post boil ph.', max_digits=5, null=True, verbose_name='Post Boil ph'),
        ),
        migrations.AddField(
            model_name='batch',
            name='post_dry_hop_oxygen_ppb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter measured oxygen (ppb).', max_digits=5, null=True, verbose_name='Post Dry Hop 02'),
        ),
        migrations.AddField(
            model_name='batch',
            name='post_transfer_oxygen_ppb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter measured oxygen (ppb).', max_digits=5, null=True, verbose_name='Post Transfer 02'),
        ),
        migrations.AddField(
            model_name='batch',
            name='pre_transfer_oxygen_ppb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter measured oxygen (ppb).', max_digits=5, null=True, verbose_name='Pre Transfer 02'),
        ),
    ]
