# Generated by Django 2.0.2 on 2018-12-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0024_auto_20180924_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='substitutions',
            field=models.TextField(blank=True, help_text='Please record ingredient substitutions here.', null=True, verbose_name='Substitutions'),
        ),
    ]
